name: Global Push & Deploy

on:
  push:
    branches: [main]
    # Only run when these change (prevents noisy failures)
    paths:
      - 'skylink360/liveMonitor.json'
      - 'masterlive/**'
      - '.github/workflows/global-push-deploy.yml'
  workflow_dispatch:

# Allow this workflow to commit back to the repo
permissions:
  contents: write

jobs:
  push-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Safe: won't fail if the JSON file doesn't exist
      - name: Prepare masterlive data
        run: |
          set -e
          mkdir -p masterlive/data
          if [ -f skylink360/liveMonitor.json ]; then
            cp skylink360/liveMonitor.json masterlive/data/
          else
            echo "No skylink360/liveMonitor.json found — skipping."
          fi

      # Only commit/push when there are actual changes
      - name: Commit and push if changed
        run: |
          set -e
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated sync $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          fi
